# Generated by Django 4.1 on 2022-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='segement',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('MPV', 'MPV')], default='Sedan', max_length=20),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
