# Generated by Django 4.1 on 2022-10-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cars_segement_alter_cars_engine_alter_cars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSearch', models.DateTimeField(auto_now_add=True)),
                ('brandName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brands')),
                ('carName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.cars')),
            ],
        ),
    ]
